"""
Adds filters for Jinja2 templates for more customisable rendering of content
"""

import re
import bleach

ALLOWED_TAGS = ["b", "i", "strong", "em", "p", "br", "a"]
ALLOWED_ATTRIBUTES = {"a": ["href", "target", "title"]}

def sanitise(value):
    """Sanitise input to prevent XSS attacks, while preserving basic formatting and safe links."""
    # Use bleach to clean the input value, allowing only specified tags and attributes, and stripping out any disallowed tags
    cleaned = bleach.clean(value, tags=ALLOWED_TAGS, attributes=ALLOWED_ATTRIBUTES, strip=True)

    # Regex sub generated by AI
    return re.sub(
        r'<a\b([^>]*)>',
        # If the anchor tag has an href attribute, add rel="noopener noreferrer" to it
        lambda match: f'{match.group(0)[:-1]} rel="noopener noreferrer">' if "href=" in match.group(1).lower() else match.group(0),
        cleaned,
        flags=re.IGNORECASE, # Make the regex case-insensitive to match 'href' in any case (e.g., HREF, Href, etc.)
    )

def init_app(app):
    # Initialise the sanitise filter for Jinja2 templates
    @app.template_filter("sanitise")
    def _sanitise_filter(value):
        # Sanitise the input value using the sanitise function defined above
        return sanitise(value)
    
    return _sanitise_filter
